### ISSUE TITLE
Variable $since of type GitTimestamp! was provided invalid value

### ISSUE THREAD

**Issue by njfamirm** [lerna-lite/lerna-lite#867]
### Describe the bug

Hi
thank's for developing this project, and also good issue template!

When I want to release the new version with lerna lite have error, no solution found when googling
I'm try update my github token, release manually and then retry 

I have manually captured several tags and releases
Can it cause problems at work?

### Expectation

release next version

### Reproduction

```sh
yarn lerna version --force-publish
```

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "https://raw.githubusercontent.com/lerna-lite/lerna-lite/main/packages/cli/schemas/lerna-schema.json",
  "version": "4.20.0",
  "npmClient": "yarn",
  "packages": [
    "packages/*"
  ],
  "loglevel": "verbose",
  "command": {
    "version": {
      "conventionalCommits": true,
      "changelog": true,
      "changelogPreset": {
        "name": "conventionalcommits",
        "types": [
          {
            "type": "feat",
            "section": "Features"
          },
          {
            "type": "feature",
            "section": "Features"
          },
          {
            "type": "fix",
            "section": "Bug Fixes"
          },
          {
            "type": "perf",
            "section": "Performance Improvements"
          },
          {
            "type": "revert",
            "section": "Reverts"
          },
          {
            "type": "refactor",
            "section": "Code Refactoring"
          },
          {
            "type": "chore",
            "section": "Miscellaneous Chores"
          },
          {
            "type": "docs",
            "section": "Documentation",
            "hidden": true
          },
          {
            "type": "doc",
            "section": "Documentation",
            "hidden": true
          },
          {
            "type": "deps",
            "section": "Dependencies update",
            "hidden": true
          },
          {
            "type": "style",
            "section": "Styles",
            "hidden": true
          },
          {
            "type": "test",
            "section": "Tests",
            "hidden": true
          },
          {
            "type": "build",
            "section": "Build System",
            "hidden": true
          },
          {
            "type": "ci",
            "section": "Continuous Integration",
            "hidden": true
          }
        ]
      },
      "changelogIncludeCommitsClientLogin": " by @%l",
      "ignoreChanges": [
        "*.md"
      ],
      "message": "release:",
      "private": true,
      "forceGitTag": true,
      "signGitTag": true,
      "signGitCommit": true,
      "push": true,
      "createRelease": "github"
    },
    "run": {
      "stream": true
    }
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv [object Object]
1 notice cli v3.4.0
2 verbose rootPath /Users/njfamirm/repo/alwatr/soffit-order
3 silly createGitHubClient
4 verbose project packages packages/*
5 info current project version 4.20.0
6 silly isAnythingCommitted
7 verbose isAnythingCommitted 1
8 silly currentBranch
9 verbose currentBranch next
10 silly remoteBranchExists
11 silly isBehindUpstream
12 silly isBehindUpstream next is behind origin/next by 0 commit(s) and ahead by 0
13 silly git-describe parsed => {"lastTagName":"v4.16.5","lastVersion":"v4.16.5","refCount":"30","sha":"120197c","isDirty":false}
14 silly git getCurrentBranchOldestCommitSinceLastTag
15 verbose exec git log v4.16.5..HEAD --format="%h %aI" --reverse
16 info oldestCommitSinceLastTag commit found since last tag: v4.16.5 - (SHA) undefined - undefined
17 silly parseGitRepo
18 verbose git config --get remote.origin.url
19 silly createGitHubClient
20 error GraphqlResponseError: Request failed due to following response errors:
20 error  - Variable $since of type GitTimestamp! was provided invalid value
20 error     at /Users/njfamirm/.yarn/berry/cache/@octokit-graphql-npm-7.1.0-9956e50359-10c0.zip/node_modules/@octokit/graphql/dist-node/index.js:113:13
20 error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
20 error     at async getGithubCommits (file:///Users/njfamirm/.yarn/berry/cache/@lerna-lite-version-npm-3.4.0-4535183461-10c0.zip/node_modules/@lerna-lite/version/dist/conventional-commits/get-github-commits.js:24:26)
```
</p></details>

<details><p>

<summary>console log</summary>
```txt
lerna-lite notice cli v3.4.0
lerna-lite verb rootPath /Users/njfamirm/repo/alwatr/soffit-order
lerna-lite verb project packages packages/*
lerna-lite info current project version 4.20.0
lerna-lite verb isAnythingCommitted 1
lerna-lite verb currentBranch next
lerna-lite verb exec git log v4.16.5..HEAD --format="%h %aI" --reverse
lerna-lite info oldestCommitSinceLastTag commit found since last tag: v4.16.5 - (SHA) undefined - undefined
lerna-lite verb git config --get remote.origin.url
lerna-lite ERR! GraphqlResponseError: Request failed due to following response errors:
lerna-lite ERR!  - Variable $since of type GitTimestamp! was provided invalid value
lerna-lite ERR!     at /Users/njfamirm/.yarn/berry/cache/@octokit-graphql-npm-7.1.0-9956e50359-10c0.zip/node_modules/@octokit/graphql/dist-node/index.js:113:13
lerna-lite ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna-lite ERR!     at async getGithubCommits (file:///Users/njfamirm/.yarn/berry/cache/@lerna-lite-version-npm-3.4.0-4535183461-10c0.zip/node_modules/@lerna-lite/version/dist/conventional-commits/get-github-commits.js:24:26)
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

GraphqlResponseError: Request failed due to following response errors:
 - Variable $since of type GitTimestamp! was provided invalid value
    at /Users/njfamirm/.yarn/berry/cache/@octokit-graphql-npm-7.1.0-9956e50359-10c0.zip/node_modules/@octokit/graphql/dist-node/index.js:113:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getGithubCommits (file:///Users/njfamirm/.yarn/berry/cache/@lerna-lite-version-npm-3.4.0-4535183461-10c0.zip/node_modules/@lerna-lite/version/dist/conventional-commits/get-github-commits.js:24:26)
    at async VersionCommand.initialize (file:///Users/njfamirm/.yarn/berry/cache/@lerna-lite-version-npm-3.4.0-4535183461-10c0.zip/node_modules/@lerna-lite/version/dist/version-command.js:164:44) {
  request: {
    query: 'query getCommits($repo: String!, $owner: String!, $branchName: String!, $pageSize: Int!, $since: GitTimestamp!) {\n' +
      '    repository(name: $repo, owner: $owner) {\n' +
      '      ref(qualifiedName: $branchName) {\n' +
      '        target { ... on Commit {\n' +
      '            history(first: $pageSize, since: $since ) {\n' +
      '              nodes { oid, message, author { name, user { login }}}\n' +
      '              pageInfo { hasNextPage, endCursor }\n' +
      '  }}}}}}',
    variables: {
      owner: 'njfamirm',
      repo: 'soffit-order',
      afterCursor: '',
      branchName: 'next',
      pageSize: 100,
      since: undefined
    }
  },
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Mon, 27 May 2024 05:57:31 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': 'repo',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '6EF1:4CCC8:31CB1D4:518BE97:665420CA',
    'x-oauth-scopes': 'admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, admin:ssh_signing_key, audit_log, codespace, copilot, delete:packages, delete_repo, gist, notifications, project, repo, user, workflow, write:discussion, write:packages',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4992',
    'x-ratelimit-reset': '1716792984',
    'x-ratelimit-resource': 'graphql',
    'x-ratelimit-used': '8',
    'x-xss-protection': '0'
  },
  response: {
    errors: [
      {
        extensions: { value: null, problems: [ [Object] ] },
        locations: [ { line: 1, column: 90 } ],
        message: 'Variable $since of type GitTimestamp! was provided invalid value'
      }
    ]
  },
  errors: [
    {
      extensions: {
        value: null,
        problems: [ { path: [], explanation: 'Expected value to not be null' } ]
      },
      locations: [ { line: 1, column: 90 } ],
      message: 'Variable $since of type GitTimestamp! was provided invalid value'
    }
  ],
  data: undefined
}
```
</p></details>

### Environment Info

  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 152.44 MB / 8.00 GB
    Shell: 5.2.26 - /opt/homebrew/bin/bash
  Binaries:
    Node: 22.2.0 - /private/var/folders/nk/6cds2s5gn2n395jpk00gn/T/xfs-b7eccce5/node
    Yarn: 4.2.2 - /private/var/folders/nk/6cds12s5gnn395jwk000gn/T/xfs-b7eccce5/yarn
    npm: 10.7.0 - /opt/homebrew/bin/npm
  Browsers:
    Safari: 17.4.1

### Used Package Manager

yarn >= 2.x

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
The issue is coming from the usage of `changelogIncludeCommitsClientLogin` and it tries to read your commits on GitHub using the GitHub GraphQL API, but the way that it works is that it needs to know all commits that happened since your last version but for unknown reason it cannot get that last version when using Git and you can see that in your logs

> 14 silly git getCurrentBranchOldestCommitSinceLastTag
> 15 verbose exec git log v4.16.5..HEAD --format="%h %aI" --reverse
> 16 info oldestCommitSinceLastTag commit found since last tag: v4.16.5 - (SHA) undefined - undefined

then further down if you look at the console error, you can see that it tries to use `undefined` on the `since` variable

> variables: {
owner: 'njfamirm',
repo: 'soffit-order',
afterCursor: '',
branchName: 'next',
pageSize: 100,
since: undefined
}

which of course fails because `undefined` is not valid. You can try running the Git command yourself, from the logs it seems to run this command which returns `undefined` and you will probably get the same result

> git log v4.16.5..HEAD --format="%h %aI" --reverse

if it's your first time running the Lerna command after migrating to it, maybe remove `changelogIncludeCommitsClientLogin` and wait until the next version or try to troubleshoot why the Git command fails. 

Also since you seem to be using `conventional-changelog-conventionalcommits` make sure that you're not using their latest version 8 because it's not supported yet.

**Comment by njfamirm** [comment]
thank's for your response 🙏🏻 

> Also since you seem to be using conventional-changelog-conventionalcommits make sure that you're not using their latest version 8 because it's not supported yet.

No, the version of this package is `7.0.2`

> if it's your first time running the Lerna command after migrating to it,

no, over 50 release created with this tool

result of this command also have many commit: 
```
git log v4.16.5..HEAD --format="%h %aI" --reverse

c6a1076 2024-05-16T10:37:42Z
a698d27 2024-05-19T07:55:54+03:30
96991e0 2024-05-19T08:11:23+03:30
cb186d1 2024-05-19T08:21:25+03:30
7e1834a 2024-05-19T08:21:40+03:30
f292db9 2024-05-19T08:24:21+03:30
3877512 2024-05-19T09:02:52+03:30
5f4d5dc 2024-05-19T10:53:16+03:30
3075e6a 2024-05-19T19:30:54+03:30
577ab05 2024-05-19T20:36:08+03:30
761241a 2024-05-20T11:02:39+03:30
17fd0b2 2024-05-20T11:10:00+03:30
e4690a7 2024-05-20T11:14:33+03:30
161d73b 2024-05-20T11:17:25+03:30
a2f9aab 2024-05-20T11:18:00+03:30
77aea71 2024-05-20T11:40:00+03:30
1fbf9c0 2024-05-20T11:40:41+03:30
3024c47 2024-05-20T11:46:33+03:30
8a2da9a 2024-05-20T11:47:02+03:30
e7dcdb4 2024-05-21T09:31:04+03:30
...
```

But! my problem is my last git tag is not v4.16.5!!
but this is not a bug from lerna-lite because:

```sh
$ git describe
v4.16.5-64-g2011602
```

I'm searching for the bug!

**Comment by ghiscoding** [comment]
I would suggest you that the next time you try the Lerna command with the `--dry-run` option, the `changelogIncludeCommitsClientLogin` is supported in dry-run mode and your changelog should be updated as well (just make sure to discard git changes after your dry-run testing is done). Finally, as you pointed out, I don't think it's a problem with Lerna-Lite, but rather a problem with your project somehow.

**Comment by njfamirm** [comment]
thank you man

**Comment by njfamirm** [comment]
I'm reset to the last git tag correct released.
and re release all new release!
and solved

**Comment by njfamirm** [comment]
I have used this tool for a long time in many projects
It works great without any problems
thank you for developing this!

But I encountered the same problem several times...
Although everything went as usual
And I still don't understand what exactly is going wrong?!

The only thing I saw was that one of the tags wasn't inside the locale (I didn't delete it manually) and that was weird.

**Comment by njfamirm** [comment]
I was able to fix the problem manually, so close this issue
but it's good if we found the exact problem

**Comment by njfamirm** [comment]
still have this issue many times

**Comment by njfamirm** [comment]
I'm try to find why this happend

in this file I try to run some parts to find why 

https://github.com/lerna-lite/lerna-lite/blob/8d01f69250abfa119bbc5ca4b9ad6c372044e3b7/packages/version/src/conventional-commits/get-commits-since-last-release.ts#L73

print the 

```
lerna-lite info oldestCommitSinceLastTag commit found since last tag: v2.7.2 - (SHA) undefined - undefined
```

so find why happen step by step, first test this part and get result:

https://github.com/lerna-lite/lerna-lite/blob/8d01f69250abfa119bbc5ca4b9ad6c372044e3b7/packages/version/src/conventional-commits/get-commits-since-last-release.ts#L55

the result of this line is: 

```
git log v4.16.5..HEAD --format="%h %aI" --reverse

c6a1076 2024-05-16T10:37:42Z
a698d27 2024-05-19T07:55:54+03:30
96991e0 2024-05-19T08:11:23+03:30
cb186d1 2024-05-19T08:21:25+03:30
```

then put above hash into the this part and boom! bug here, and why?

https://github.com/lerna-lite/lerna-lite/blob/8d01f69250abfa119bbc5ca4b9ad6c372044e3b7/packages/version/src/conventional-commits/get-commits-since-last-release.ts#L71

```
/^"?([0-9a-f]+)\s([0-9\-|+T:]*)"?$/.exec('c6a1076 2024-05-16T10:37:42Z')
```

**Comment by ghiscoding** [comment]
That's a good find, it looks like your git timestamp is quite different sometime (I'm not sure why git timestamp format would differ), and if you add `Z` and `.` in the date regex part, it works better. 

with the updated regex `^"?([0-9a-f]+)\s([0-9\-Z.|+T:]*)"?$` it passes

![image](https://github.com/lerna-lite/lerna-lite/assets/643976/0d33ea66-4a88-4998-8000-cc6f599171ba)

I'd be happy to receive a PR from your side to fix this issue.

**Comment by njfamirm** [comment]
ok, thanks

**Comment by AliMD** [comment]
Im still have same issue (in same time zone) in version 3.7.0!

**Comment by AliMD** [comment]
> I was able to fix the problem manually, so close this issue but it's good if we found the exact problem

how exactly?!

**Comment by AliMD** [comment]
```
lerna-lite notice cli v3.7.0
lerna-lite verb rootPath /Volumes/AlwatrMac/repositories/flight-finder
lerna-lite verb project packages packages/app packages/types
lerna-lite info current project version 1.0.0-1
lerna-lite verb isAnythingCommitted 1
lerna-lite verb currentBranch next
lerna-lite verb exec git log --oneline --format="%h %aI" --reverse --max-parents=0 HEAD
lerna-lite info oldestCommitSinceLastTag commit found since last tag: undefined - (SHA) undefined - undefined
lerna-lite verb git config --get remote.origin.url
lerna-lite ERR! GraphqlResponseError: Request failed due to following response errors:
lerna-lite ERR!  - Variable $since of type GitTimestamp! was provided invalid value
lerna-lite ERR!     at file:///Users/alimihandoost/.yarn/berry/cache/@octokit-graphql-npm-8.1.1-2d1a29021f-10c0.zip/node_modules/@octokit/graphql/dist-bundle/index.js:89:13
lerna-lite ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna-lite ERR!     at async getGithubCommits (file:///Users/alimihandoost/.yarn/berry/cache/@lerna-lite-version-npm-3.7.0-4ab343f63c-10c0.zip/node_modules/@lerna-lite/version/dist/conventional-commits/get-github-commits.js:24:26)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

GraphqlResponseError: Request failed due to following response errors:
 - Variable $since of type GitTimestamp! was provided invalid value
    at file:///Users/alimihandoost/.yarn/berry/cache/@octokit-graphql-npm-8.1.1-2d1a29021f-10c0.zip/node_modules/@octokit/graphql/dist-bundle/index.js:89:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getGithubCommits (file:///Users/alimihandoost/.yarn/berry/cache/@lerna-lite-version-npm-3.7.0-4ab343f63c-10c0.zip/node_modules/@lerna-lite/version/dist/conventional-commits/get-github-commits.js:24:26)
    at async VersionCommand.initialize (file:///Users/alimihandoost/.yarn/berry/cache/@lerna-lite-version-npm-3.7.0-4ab343f63c-10c0.zip/node_modules/@lerna-lite/version/dist/version-command.js:165:44) {
  errors: [
    {
      extensions: {
        value: null,
        problems: [ { path: [], explanation: 'Expected value to not be null' } ]
      },
      locations: [ { line: 1, column: 90 } ],
      message: 'Variable $since of type GitTimestamp! was provided invalid value'
    }
  ],
  data: undefined,
  request: {
    query: 'query getCommits($repo: String!, $owner: String!, $branchName: String!, $pageSize: Int!, $since: GitTimestamp!) {\n' +
      '    repository(name: $repo, owner: $owner) {\n' +
      '      ref(qualifiedName: $branchName) {\n' +
      '        target { ... on Commit {\n' +
      '            history(first: $pageSize, since: $since ) {\n' +
      '              nodes { oid, message, author { name, user { login }}}\n' +
      '              pageInfo { hasNextPage, endCursor }\n' +
      '  }}}}}}',
    variables: {
      owner: 'AliMD',
      repo: 'flight-finder',
      afterCursor: '',
      branchName: 'next',
      pageSize: 100,
      since: undefined
    }
  },
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 10 Jul 2024 12:10:59 GMT',
    'github-authentication-token-expiration': '2024-11-08 00:00:00 +0330',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '48AD:35F308:1D20EB4:1D713D6:668E7A53',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '5000',
    'x-ratelimit-reset': '1720617059',
    'x-ratelimit-resource': 'graphql',
    'x-ratelimit-used': '0',
    'x-xss-protection': '0'
  },
  response: {
    errors: [
      {
        extensions: { value: null, problems: [ [Object] ] },
        locations: [ { line: 1, column: 90 } ],
        message: 'Variable $since of type GitTimestamp! was provided invalid value'
      }
    ]
  }
}

Node.js v21.7.1
```

**Comment by AliMD** [comment]
> git log v1.0.0..HEAD --format="%h %aI" --reverse

ec672ed 2024-07-10T15:51:06+03:30

**Comment by ghiscoding** [comment]
by reading the logs that you have, it doesn't run the command that you think it does, it's not running `git log v1.0.0..HEAD --format="%h %aI" --reverse` because it doesn't find the last tag and so the first `if` condition (shown below) is false

https://github.com/lerna-lite/lerna-lite/blob/68f82381216acf2ee02f105045127fe1221a603e/packages/version/src/conventional-commits/get-commits-since-last-release.ts#L52-L56

so it goes into the `else` section instead which is this (as per your log `exec git log --oneline --format="%h %aI" --reverse --max-parents=0 HEAD`)
https://github.com/lerna-lite/lerna-lite/blob/68f82381216acf2ee02f105045127fe1221a603e/packages/version/src/conventional-commits/get-commits-since-last-release.ts#L64-L69

and this command does not return the required `since` date which is why the GitHub GraphQL query to get the git commits infos fails. 

I'll add some code in place to avoid the error to throw **but** this is still a problem on your end. It's not running what you think it does...
