### ISSUE TITLE
Variable $since of type GitTimestamp! was provided invalid value

### ISSUE THREAD

**Issue by StarpTech** [lerna-lite/lerna-lite#906]
### Describe the bug

Hi, we run into this error after we triggered a release for a package without any new changes.

 Logs - https://github.com/wundergraph/cosmo/actions/runs/10238763213/job/28323594600
 
```
lerna publish -y
```

Independent mode: [X]

```
starptech

> wundergraph-cosmo@0.0.1 release /home/runner/work/cosmo/cosmo
> lerna publish -y

lerna-lite notice cli v3.3.1
lerna-lite verb rootPath /home/runner/work/cosmo/cosmo
lerna-lite info versioning independent
lerna-lite info ci enabled
lerna-lite verb project packages cli composition shared connect controlplane router otelcollector graphqlmetrics studio keycloak cdn-server cdn-server/cdn aws-lambda-router playground
lerna-lite verb session 16a66d49d396b99f
lerna-lite verb user-agent lerna/3.3.1/node@v20.16.0+x64 (linux)
lerna-lite verb rootPath /home/runner/work/cosmo/cosmo
lerna-lite verb project packages cli composition shared connect controlplane router otelcollector graphqlmetrics studio keycloak cdn-server cdn-server/cdn aws-lambda-router playground
lerna-lite verb isAnythingCommitted 1
lerna-lite verb currentBranch main
lerna-lite verb git-describe.sync "*@*" => "router@0.101.2-0-gb283a6a0"
lerna-lite verb exec git log router@0.101.2..HEAD --format="%h %aI" --reverse
lerna-lite info oldestCommitSinceLastTag commit found since last tag: router@0.101.2 - (SHA) undefined - undefined
lerna-lite verb git config --get remote.origin.url
lerna-lite ERR! GraphqlResponseError: Request failed due to following response errors:
lerna-lite ERR!  - Variable $since of type GitTimestamp! was provided invalid value
lerna-lite ERR!     at /home/runner/work/cosmo/cosmo/node_modules/.pnpm/@octokit+graphql@7.0.2/node_modules/@octokit/graphql/dist-node/index.js:1[13](https://github.com/wundergraph/cosmo/actions/runs/10238763213/job/28323594600#step:9:14):13
lerna-lite ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna-lite ERR!     at async getGithubCommits (file:///home/runner/work/cosmo/cosmo/node_modules/.pnpm/@lerna-lite+version@3.3.1_@lerna-lite+publish@3.3.1_typescript@5.5.2/node_modules/@lerna-lite/version/dist/conventional-commits/get-github-commits.js:24:26)
lerna-lite ERR! GraphqlResponseError: Request failed due to following response errors:
lerna-lite ERR!  - Variable $since of type GitTimestamp! was provided invalid value
lerna-lite ERR!     at /home/runner/work/cosmo/cosmo/node_modules/.pnpm/@octokit+graphql@7.0.2/node_modules/@octokit/graphql/dist-node/index.js:113:13
lerna-lite ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna-lite ERR!     at async getGithubCommits (file:///home/runner/work/cosmo/cosmo/node_modules/.pnpm/@lerna-lite+version@3.3.1_@lerna-lite+publish@3.3.1_typescript@5.5.2/node_modules/@lerna-lite/version/dist/conventional-commits/get-github-commits.js:24:26)
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

GraphqlResponseError: Request failed due to following response errors:
 - Variable $since of type GitTimestamp! was provided invalid value
    at /home/runner/work/cosmo/cosmo/node_modules/.pnpm/@octokit+graphql@7.0.2/node_modules/@octokit/graphql/dist-node/index.js:113:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getGithubCommits (file:///home/runner/work/cosmo/cosmo/node_modules/.pnpm/@lerna-lite+version@3.3.1_@lerna-lite+publish@3.3.1_typescript@5.5.2/node_modules/@lerna-lite/version/dist/conventional-commits/get-github-commits.js:24:26)
    at async VersionCommand.initialize (file:///home/runner/work/cosmo/cosmo/node_modules/.pnpm/@lerna-lite+version@3.3.1_@lerna-lite+publish@3.3.1_typescript@5.5.2/node_modules/@lerna-lite/version/dist/version-command.js:[15](https://github.com/wundergraph/cosmo/actions/runs/10238763213/job/28323594600#step:9:16)9:44) {
  request: {
    query: 'query getCommits($repo: String!, $owner: String!, $branchName: String!, $pageSize: Int!, $since: GitTimestamp!) {\n' +
      '    repository(name: $repo, owner: $owner) {\n' +
      '      ref(qualifiedName: $branchName) {\n' +
      '        target { ... on Commit {\n' +
      '            history(first: $pageSize, since: $since ) {\n' +
      '              nodes { oid, message, author { name, user { login }}}\n' +
      '              pageInfo { hasNextPage, endCursor }\n' +
      '  }}}}}}',
    variables: {
      owner: 'wundergraph',
      repo: 'cosmo',
      afterCursor: '',
      branchName: 'main',
      pageSize: 100,
      since: undefined
    }
  },
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Sun, 04 Aug 2024 19:38:58 GMT',
    'github-authentication-token-expiration': '2025-03-15 00:00:00 +0100',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '87C0:1AE375:760E941:DA8EC98:66AFD8D2',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4966',
    'x-ratelimit-reset': '1722803856',
    'x-ratelimit-resource': 'graphql',
    'x-ratelimit-used': '34',
    'x-xss-protection': '0'
  },
  response: {
    errors: [
      {
        extensions: { value: null, problems: [ [Object] ] },
        locations: [ { line: 1, column: 90 } ],
        message: 'Variable $since of type GitTimestamp! was provided invalid value'
      }
    ]
  },
  errors: [
    {
      extensions: {
        value: null,
        problems: [ { path: [], explanation: 'Expected value to not be null' } ]
      },
      locations: [ { line: 1, column: 90 } ],
      message: 'Variable $since of type GitTimestamp! was provided invalid value'
    }
  ],
  data: undefined
}

Node.js v20.[16](https://github.com/wundergraph/cosmo/actions/runs/10238763213/job/28323594600#step:9:17).0
 ELIFECYCLE  Command failed with exit code 1.
```

### Expectation

No error.

### Reproduction

Not sure how. You could publish an package and then try to release it again without any changes.

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

### Environment Info

  System:
    OS: macOS 14.5
    CPU: (16) arm64 Apple M3 Max
    Memory: 11.19 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.1/bin/npm
    pnpm: 8.15.5 - /opt/homebrew/bin/pnpm
    bun: 1.1.12 - ~/.bun/bin/bun
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 17.5
  npmPackages:
    @lerna-lite/cli: 3.3.1 => 3.3.1 
    @lerna-lite/publish: 3.3.1 => 3.3.1 
    @lerna-lite/version: 3.3.1 => 3.3.1 

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by StarpTech** [comment]
It looks like this has been addressed in https://github.com/lerna-lite/lerna-lite/releases/tag/v3.7.1
